using System.Collections.Generic;

// Scene-scan registry mapping a saved SaveId string back to the live
// instance sitting in the loaded scene — every SaveId self-registers on
// enable/disable, so SaveManager.Load doesn't need to walk the scene
// itself for each lookup.
public static class SaveIdRegistry
{
    private static readonly Dictionary<string, SaveId> byId = new Dictionary<string, SaveId>();

    public static void Register(SaveId saveId)
    {
        if (saveId == null || string.IsNullOrEmpty(saveId.Id)) return;
        byId[saveId.Id] = saveId;
    }

    public static void Unregister(SaveId saveId)
    {
        // Null/empty Id guard added 2026-08-17 -- a SaveId auto-added via
        // RequireComponent during a runtime AddComponent (e.g.
        // SaveManager.RestorePlacedPieces re-instantiating a missing
        // structure) doesn't reliably get its id generated by Reset()
        // (same gotcha the original placement-time fix already covers
        // elsewhere). Calling AssignId on such a SaveId hit this method
        // with a null Id and crashed on Dictionary.TryGetValue(null, ...)
        // -- ArgumentNullException, confirmed live, which silently aborted
        // the rest of that restore iteration (the villageName restore
        // step never ran). Same defensive guard Register already has.
        if (saveId == null || string.IsNullOrEmpty(saveId.Id)) return;
        if (byId.TryGetValue(saveId.Id, out var current) && current == saveId)
            byId.Remove(saveId.Id);
    }

    public static SaveId Find(string id) =>
        !string.IsNullOrEmpty(id) && byId.TryGetValue(id, out var found) ? found : null;
}
